import {
  ArrowLeft,
  BadgeCheck,
  Bell,
  Bot,
  BookOpen,
  Building2,
  CalendarDays,
  Camera,
  Check,
  ClipboardCheck,
  ClipboardPen,
  ChevronRight,
  CircleAlert,
  CircleHelp,
  Clock3,
  CloudDownload,
  Download,
  FileCheck,
  FileText,
  GraduationCap,
  Home,
  Info,
  Image as ImageIcon,
  Languages,
  Landmark,
  LockKeyhole,
  LogOut,
  MapPin,
  MessageCircle,
  Moon,
  Pencil,
  PlusCircle,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  UserRound,
  Wallet,
  X,
} from 'lucide-react-native';
import { colors } from '../theme';

const iconMap = {
  // Existing semantic aliases keep screen behavior intact while using Lucide everywhere.
  'home-outline': Home,
  'school-outline': GraduationCap,
  'document-text-outline': FileText,
  'chatbubbles-outline': MessageCircle,
  'bot-outline': Bot,
  'person-outline': User,
  'person-circle-outline': UserRound,
  'chevron-forward': ChevronRight,
  'shield-checkmark-outline': BadgeCheck,
  'shield-outline': Shield,
  'lock-closed-outline': LockKeyhole,
  'checkmark-circle': BadgeCheck,
  'time-outline': Clock3,
  'alert-circle-outline': CircleAlert,
  'search-outline': Search,
  'notifications-outline': Bell,
  'settings-outline': Settings,
  'help-circle-outline': CircleHelp,
  'language-outline': Languages,
  'sunny-outline': Sun,
  'moon-outline': Moon,
  'arrow-back': ArrowLeft,
  'cloud-download-outline': CloudDownload,
  send: Send,
  'add-circle-outline': PlusCircle,
  'wallet-outline': Wallet,
  'business-outline': Building2,
  'calendar-outline': CalendarDays,
  'log-out-outline': LogOut,
  close: X,
  checkmark: Check,
  'information-circle-outline': Info,
  'graduation-cap': GraduationCap,
  'badge-check': BadgeCheck,
  'clipboard-check': ClipboardCheck,
  'clipboard-pen': ClipboardPen,
  'landmark': Landmark,
  'calendar-days': CalendarDays,
  'clock-3': Clock3,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  'file-check': FileCheck,
  'map-pin': MapPin,
  'book-open': BookOpen,
  camera: Camera,
  image: ImageIcon,
  upload: Upload,
  download: Download,
  pencil: Pencil,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  'circle-alert': CircleAlert,
  info: Info,
};

export type AppIconName = keyof typeof iconMap;

export function Icon({ name, size = 20, color = colors.textSecondary, strokeWidth = 2 }: {
  name: AppIconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) {
  const LucideIcon = iconMap[name];
  return <LucideIcon size={size} color={color} strokeWidth={strokeWidth} />;
}
