import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ActionButton } from '../src/components/ActionButton';
import { Card } from '../src/components/Card';
import { Heading, Page } from '../src/components/Page';
import { StatusPill } from '../src/components/StatusPill';
import { Icon } from '../src/components/Icon';
import { useApp } from '../src/context/AppContext';
import { colors, createThemedStyles } from '../src/theme';

const stages=['Draft','Submitted','Under Verification','Action Required','Verified','Sanctioned','Disbursement Processing','Disbursed'];
function stageIndex(status:string){const s=status.toLowerCase();if(/draft/.test(s))return 0;if(/action|required|deficien/.test(s))return 3;if(/disbursed/.test(s))return 7;if(/disburs|payment/.test(s))return 6;if(/sanction/.test(s))return 5;if(/verified/.test(s))return 4;if(/verification/.test(s))return 2;if(/submit/.test(s))return 1;return -1;}
export default function ApplicationsScreen(){const {data}=useApp();const router=useRouter();const applications=data?.applications||[];const drafts=data?.drafts||{};return <Page><Heading eyebrow="UNIFIED APPLICATION TRACKER" title="My applications" subtitle="Follow the current stage and review actions or deficiencies only when they are present in your application data."/>
  {applications.map(application=>{const current=stageIndex(application.status);const actionCount=application.pendingActions?.length||0;return <Card key={application.id}><View style={styles.row}><View style={styles.tile}><Icon name="clipboard-check"/></View><View style={{flex:1}}><Text style={styles.title}>{application.name}</Text><Text style={styles.meta}>{application.isSubmitted===false?'Not submitted yet':application.submittedAt||application.submitted?`Submitted ${application.submittedAt||application.submitted}`:application.isSubmitted===true?'Submission date not available':'Date not available'}</Text></View><StatusPill label={application.status} tone={/action|required|deficien/i.test(application.status)?'pending':'info'}/></View>
    <View style={styles.track}>{stages.map((stage,index)=>{const isCurrent=current===index;const completed=current>=0&&index<current;return <View key={stage} style={styles.stage}><View style={[styles.bullet,completed&&styles.completed,isCurrent&&styles.currentBullet]}/><View style={styles.stageTextWrap}><Text style={[styles.stageText,isCurrent&&styles.currentText]}>{stage}{isCurrent?' · current':''}</Text>{!completed&&!isCurrent?<Text style={styles.notReported}>Not reported</Text>:null}</View></View>})}</View>
    <Text style={styles.currentStage}>Recorded stage: {application.stage}</Text>
    {application.deficiency?<View style={styles.issue}><Icon name="triangle-alert" color={colors.warning}/><View style={{flex:1}}><Text style={styles.issueTitle}>Information requires attention</Text><Text style={styles.meta}>{application.deficiency}</Text><Pressable accessibilityRole="button" onPress={()=>router.push({pathname:'/apply/[id]',params:{id:application.scholarshipId}})}><Text style={styles.actionLink}>Fix now</Text></Pressable></View></View>:null}
    {application.pendingActions?.map(action=><View key={action.id} style={styles.action}><Text style={styles.issueTitle}>{action.title}</Text><Text style={styles.meta}>{action.explanation}</Text><Pressable accessibilityRole="button" onPress={()=>router.push({pathname:'/apply/[id]',params:{id:application.scholarshipId}})}><Text style={styles.actionLink}>Review / fix now</Text></Pressable></View>)}
    {!actionCount&&!application.deficiency?<Text style={styles.meta}>No pending action or deficiency is recorded for this application.</Text>:null}
    <View style={styles.footer}><Pressable accessibilityRole="button" onPress={()=>router.push({pathname:'/apply/[id]',params:{id:application.scholarshipId}})}><Text style={styles.actionLink}>Continue application</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>router.push('/payments')}><Text style={styles.actionLink}>Payment / DBT</Text></Pressable></View>
    <Text style={styles.demo}>Prototype application record · not a government portal status</Text>
  </Card>})}
  {Object.entries(drafts).map(([scholarshipId,draft])=>{const scheme=data?.scholarships.find(item=>item.id===scholarshipId);if(!scheme||applications.some(app=>app.scholarshipId===scholarshipId))return null;return <Pressable key={scholarshipId} onPress={()=>router.push({pathname:'/apply/[id]',params:{id:scholarshipId}})}><Card><View style={styles.row}><View style={styles.tile}><Icon name="clipboard-pen" color={colors.accent}/></View><View style={{flex:1}}><Text style={styles.title}>{scheme.name}</Text><Text style={styles.meta}>Incomplete draft · Step {String(draft.currentStep||1)} of 5</Text></View><Icon name="chevron-forward"/></View><Text style={styles.demo}>Saved in this prototype only. Review your details before continuing.</Text></Card></Pressable>})}
  {!applications.length&&!Object.keys(drafts).length?<Card><View style={styles.empty}><Icon name="clipboard-check" size={29} color={colors.accent}/><Text style={styles.title}>No applications yet</Text><Text style={styles.meta}>Your application stage, actions, sanction and payment status will appear here when available.</Text></View></Card>:null}
  <ActionButton title="Browse the five schemes" onPress={()=>router.push('/(tabs)/scholarships')}/>
</Page>}
const styles=createThemedStyles((theme) => ({row:{flexDirection:'row',alignItems:'center',gap:10},tile:{width:40,height:40,borderRadius:12,backgroundColor:theme.surfaceStrong,alignItems:'center',justifyContent:'center'},title:{fontSize:12,fontWeight:'800',color:theme.textPrimary},meta:{fontSize:10,color:theme.textMuted,marginTop:5,lineHeight:15},track:{marginVertical:15,paddingLeft:4},stage:{flexDirection:'row',alignItems:'flex-start',gap:9,minHeight:35},bullet:{width:15,height:15,borderRadius:8,backgroundColor:theme.surfaceStrong,borderWidth:1,borderColor:theme.border,marginTop:2},completed:{backgroundColor:theme.secondary,borderColor:theme.accent},currentBullet:{backgroundColor:theme.primary,borderColor:theme.accent},stageTextWrap:{flex:1},stageText:{fontSize:11,color:theme.textMuted},currentText:{color:theme.textPrimary,fontWeight:'700'},notReported:{fontSize:9,color:theme.disabledText,marginTop:2},currentStage:{fontSize:11,color:theme.textSecondary,fontWeight:'600',marginBottom:6},issue:{flexDirection:'row',alignItems:'flex-start',gap:9,padding:11,borderRadius:11,backgroundColor:theme.surfaceStrong,marginTop:10},issueTitle:{fontSize:11,fontWeight:'700',color:theme.warning},action:{paddingVertical:8,borderTopWidth:1,borderColor:theme.border},footer:{flexDirection:'row',justifyContent:'space-between',marginTop:12,paddingTop:10,borderTopWidth:1,borderColor:theme.border},actionLink:{fontSize:11,color:theme.accent,fontWeight:'700',marginTop:6},demo:{fontSize:9,color:theme.textMuted,marginTop:9},empty:{alignItems:'center',paddingVertical:8}}));
