import { useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Card } from '../src/components/Card';
import { Heading, Page } from '../src/components/Page';
import { StatusPill } from '../src/components/StatusPill';
import { Icon } from '../src/components/Icon';
import { useApp } from '../src/context/AppContext';
import { getIntegrationStatuses, loadIntegrationStatuses } from '../src/services/integrationStatus';
import { colors, createThemedStyles } from '../src/theme';

export default function IntegrationsScreen(){const {data}=useApp();const router=useRouter();const [integrations,setIntegrations]=useState(()=>getIntegrationStatuses(Boolean(data?.digilocker.configured)));useEffect(()=>{let mounted=true;void loadIntegrationStatuses().then(statuses=>{if(mounted)setIntegrations(statuses)});return()=>{mounted=false}},[]);return <Page><Heading eyebrow="UNIFIED VERIFICATION & INTEGRATION LAYER" title="Verification status" subtitle="Connected services are shown honestly. Each government or issuer source requires authorized access and student consent."/>
  {integrations.map(item=><Card key={item.id}><View style={styles.row}><View style={styles.tile}><Icon name={item.id==='digilocker'?'lock-closed-outline':item.id==='dbt'?'landmark':item.id==='scholarship-portal'?'graduation-cap':item.id==='education-source'?'book-open':'badge-check'} color={item.state==='proposed'?colors.warning:colors.accent}/></View><View style={{flex:1}}><Text style={styles.title}>{item.label}</Text><Text style={styles.meta}>{item.description}</Text></View></View><View style={styles.statusLine}><StatusPill label={item.state==='proposed'?'Proposed Integration':item.state==='demo'?'Demo / not connected':'Credentials configured'} tone={item.state==='proposed'?'pending':'info'}/></View></Card>)}
  <Card><Text style={styles.title}>Verification flow</Text>{['Student data with consent','Authorized source','Verification service','Match / mismatch / unavailable','Rules engine','Continue or manual review'].map((step,index)=><View key={step} style={styles.flowRow}><View style={styles.number}><Text style={styles.numberText}>{index+1}</Text></View><Text style={styles.meta}>{step}</Text></View>)}</Card>
  <Card><View style={styles.row}><Icon name="triangle-alert" color={colors.warning}/><View style={{flex:1}}><Text style={styles.title}>Manual exception handling</Text><Text style={styles.meta}>When no authorized source can verify a document, the state is unavailable or needs manual review. A mismatch does not label a document as fake.</Text></View></View><Text style={styles.ocr}>OCR can assist with extraction, readability and field comparison. It cannot decide whether an ST certificate is genuine.</Text></Card>
  <Pressable accessibilityRole="button" onPress={()=>router.push('/(tabs)/documents')} style={styles.link}><Text style={styles.linkText}>Open Document Wallet</Text><Icon name="chevron-forward" size={17}/></Pressable>
</Page>}
const styles=createThemedStyles((theme) => ({row:{flexDirection:'row',alignItems:'center',gap:11},tile:{width:42,height:42,borderRadius:12,backgroundColor:theme.surfaceStrong,alignItems:'center',justifyContent:'center'},title:{fontSize:12,fontWeight:'800',color:theme.textPrimary},meta:{fontSize:10,color:theme.textMuted,lineHeight:16,marginTop:4,flex:1},statusLine:{marginTop:10},flowRow:{flexDirection:'row',alignItems:'center',gap:10,marginTop:12},number:{width:23,height:23,borderRadius:12,backgroundColor:theme.surfaceStrong,alignItems:'center',justifyContent:'center'},numberText:{fontSize:10,color:theme.accent,fontWeight:'700'},ocr:{fontSize:10,color:theme.warning,lineHeight:16,marginTop:12},link:{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:7,paddingVertical:12},linkText:{color:theme.accent,fontSize:12,fontWeight:'700'}}));
