import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useMemo, useRef, useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { ActionButton } from '../../src/components/ActionButton';
import { Card } from '../../src/components/Card';
import { Heading, Page } from '../../src/components/Page';
import { Icon } from '../../src/components/Icon';
import { useApp } from '../../src/context/AppContext';
import { checkScholarshipConflict } from '../../src/services/scholarshipRules';
import { colors, createThemedStyles } from '../../src/theme';

export default function ApplyScreen(){
  const {id}=useLocalSearchParams<{id:string}>();const {data,saveDraft}=useApp();const router=useRouter();
  const [step,setStep]=useState(1);const [studentName,setStudentName]=useState('');const [dob,setDob]=useState('');const [address,setAddress]=useState('');const [email,setEmail]=useState('');const [education,setEducation]=useState('');const [institution,setInstitution]=useState('');const [income,setIncome]=useState('');const [bankReference,setBankReference]=useState('');const [conflictReviewed,setConflictReviewed]=useState(false);const hydrated=useRef(false);
  const scholarship=data?.scholarships.find(s=>s.id===id);
  const conflict=useMemo(()=>scholarship&&data?checkScholarshipConflict(scholarship,data.applications,data.scholarships):null,[scholarship,data]);
  const steps=['Student details','Education','Family income','DBT details','Documents'];
  useEffect(()=>{if(!data||hydrated.current)return;hydrated.current=true;const draft=data.drafts?.[id]||{};setStudentName(String(draft.studentName||data.profile.name||''));setDob(String(draft.dob||data.profile.dob||''));setAddress(String(draft.address||data.profile.address||''));setEmail(String(draft.email||data.profile.email||''));setEducation(String(draft.education||data.profile.education||''));setInstitution(String(draft.institution||''));setIncome(String(draft.familyIncome||data.profile.familyIncome||''));setBankReference(String(draft.bankReference||''));const savedStep=Number(draft.currentStep);if(savedStep>=1&&savedStep<=5)setStep(savedStep);},[data,id]);
  if(!scholarship)return null;
  async function next(){try{if(step<5){const nextStep=step+1;await saveDraft(id,{currentStep:nextStep,studentName,dob,address,email,education,institution,familyIncome:income,bankReference});setStep(nextStep);return;}await saveDraft(id,{currentStep:5,studentName,dob,address,email,education,institution,familyIncome:income,bankReference});router.push({pathname:'/review',params:{id}});}catch{ /* Keep entered values on screen if draft storage is unavailable. */}}
  if(conflict&&conflict.state!=='clear'&&!conflictReviewed){return <Page><Heading eyebrow="RULE-BASED CONFLICT CHECK" title="Review existing applications" subtitle="ADI SETU checks only configured scheme rules. It does not assume that all scholarships are incompatible."/><Card><View style={styles.row}><Icon name={conflict.state==='blocked'?'triangle-alert':'information-circle-outline'} color={conflict.state==='blocked'?colors.warning:colors.accent}/><Text style={styles.conflictTitle}>{conflict.state==='blocked'?'Configured rule requires review':'Another application is recorded'}</Text></View><Text style={styles.hint}>{conflict.message}</Text>{conflict.activeApplications.map(application=><Text key={application.id} style={styles.activeRecord}>{application.name} · {application.status}</Text>)}{conflict.applicableRule?<Text style={styles.rule}>Configured scheme rule: {conflict.applicableRule}</Text>:null}<Text style={styles.hint}>These records are prototype application data, not proof of an active scholarship benefit.</Text></Card>{conflict.state==='blocked'?<ActionButton title="Back to scheme details" onPress={()=>router.back()}/>:<ActionButton title="I reviewed this information — continue" onPress={()=>setConflictReviewed(true)}/>}<ActionButton title="Cancel" secondary onPress={()=>router.back()}/></Page>}
  return <Page><Heading eyebrow={`STEP ${step} OF 5`} title={steps[step-1]} subtitle={`${scholarship.name} · Review reused details before continuing.`}/>
    {conflict?<Card style={styles.conflictCard}><View style={styles.row}><Icon name="badge-check" color={colors.accent}/><Text style={styles.conflictTitle}>Rule-based conflict check</Text></View><Text style={styles.hint}>{conflict.message}</Text></Card>:null}
    <View style={styles.steps}>{steps.map((label,index)=><View key={label} style={[styles.dot,index<step&&styles.active]}><Text style={[styles.dotText,index<step&&styles.activeText]}>{index+1}</Text></View>)}</View>
    <Card>
      {step===1?<><Text style={styles.section}>Student details</Text><Text style={styles.hint}>Sample details are prefilled for review. You can edit them for this draft.</Text><Field title="Full name" value={studentName} onChangeText={setStudentName} placeholder="Enter your name"/><Field title="Date of birth" value={dob} onChangeText={setDob} placeholder="Enter date of birth"/><Field title="Address" value={address} onChangeText={setAddress} placeholder="Enter your address"/><Field title="Email address" value={email} onChangeText={setEmail} placeholder="Enter email address"/></>:null}
      {step===2?<><Text style={styles.section}>Education & institution</Text><Field title="Education level" value={education} onChangeText={setEducation} placeholder="Enter your education level"/><Field title="Institution name" value={institution} onChangeText={setInstitution} placeholder="Enter your institution"/></>:null}
      {step===3?<><Text style={styles.section}>Family income</Text><Field title="Annual family income" value={income} onChangeText={setIncome} placeholder="Enter if required by the scheme" keyboardType="numeric"/><Text style={styles.hint}>The exact income criteria are not configured in this prototype. Check official scheme details.</Text></>:null}
      {step===4?<><Text style={styles.section}>Bank / DBT details</Text><Field title="Optional reference (do not enter full account number)" value={bankReference} onChangeText={setBankReference} placeholder="Optional note or last four characters"/><Text style={styles.hint}>No DBT source is connected. Do not enter passwords, PINs, or full bank account details.</Text></>:null}
      {step===5?<><Text style={styles.section}>Document wallet</Text>{data?.documents.length?data.documents.map(doc=><View key={doc.id} style={styles.docRow}><Icon name="document-text-outline" color={colors.accent}/><View style={{flex:1}}><Text style={styles.fieldTitle}>{doc.name}</Text><Text style={styles.hint}>{doc.issuer} · {doc.status}</Text></View></View>):<Text style={styles.hint}>No documents are saved. Document requirements are not configured for this scheme. Manual verification may be required when an authorized source is unavailable.</Text>}<Text style={[styles.hint,{marginTop:12}]}>Review the information before continuing. Nothing is submitted automatically.</Text></>:null}
    </Card>
    <ActionButton title={step===5?'Review & confirm':'Save draft and continue'} onPress={()=>void next()}/>{step>1?<ActionButton title="Previous" secondary onPress={()=>setStep(step-1)}/>:null}
    <Text style={styles.prototype}>Prototype application flow · no data is submitted to a government portal.</Text>
  </Page>
}
function Field(props:{title:string;value:string;placeholder:string;onChangeText:(value:string)=>void;keyboardType?:'numeric'}){return <View style={styles.field}><Text style={styles.fieldTitle}>{props.title}</Text><TextInput value={props.value} onChangeText={props.onChangeText} placeholder={props.placeholder} keyboardType={props.keyboardType} style={styles.input} placeholderTextColor={colors.textMuted}/></View>}
const styles=createThemedStyles((theme) => ({steps:{flexDirection:'row',justifyContent:'space-between',marginBottom:15},dot:{width:29,height:29,borderRadius:16,backgroundColor:theme.surfaceStrong,alignItems:'center',justifyContent:'center'},active:{backgroundColor:theme.primary},dotText:{fontSize:11,color:theme.textMuted,fontWeight:'700'},activeText:{color:theme.textPrimary},section:{fontSize:13,fontWeight:'800',color:theme.textPrimary,marginBottom:9},field:{marginTop:10},fieldTitle:{fontSize:10,fontWeight:'700',color:theme.textMuted,marginBottom:5},input:{minHeight:43,borderWidth:1,borderColor:theme.border,borderRadius:10,paddingHorizontal:11,fontSize:12,color:theme.textSecondary,backgroundColor:theme.input},hint:{fontSize:11,color:theme.textMuted,lineHeight:17,marginTop:7},docRow:{flexDirection:'row',gap:9,alignItems:'center',marginTop:11},prototype:{fontSize:10,color:theme.textMuted,textAlign:'center',marginTop:12},row:{flexDirection:'row',alignItems:'center',gap:10},conflictTitle:{fontSize:13,fontWeight:'800',color:theme.textPrimary,flex:1},conflictCard:{padding:12,marginBottom:8},activeRecord:{fontSize:12,color:theme.textSecondary,marginTop:11},rule:{fontSize:11,color:theme.warning,lineHeight:16,marginTop:10}}));
