import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Card } from '../../src/components/Card';
import { Heading, Page } from '../../src/components/Page';
import { StatusPill } from '../../src/components/StatusPill';
import { ActionButton } from '../../src/components/ActionButton';
import { Icon } from '../../src/components/Icon';
import { useApp } from '../../src/context/AppContext';
import { api } from '../../src/services/api';
import { colors, createThemedStyles } from '../../src/theme';

export default function DocumentsScreen(){const {data}=useApp();const router=useRouter();const documents=data?.documents||[];const [checking,setChecking]=useState<string|null>(null);const [results,setResults]=useState<Record<string,string>>({});async function checkSource(document:{id:string;name:string;category?:string;sourceType?:string}){setChecking(document.id);const result=await api.post<{message?:string;status?:string}>('/verification/check',{id:document.id,name:document.name,category:document.category,sourceType:document.sourceType});setResults(current=>({...current,[document.id]:result.message||'Verification could not be completed through the available source. Manual official verification may be required.'}));setChecking(null)}return <Page><Heading title="Your documents" subtitle="Review document source and status. DigiLocker access requires authorization; account login alone does not verify ST status."/>
  <Card><View style={styles.row}><View style={styles.tile}><Icon name="lock-closed-outline" color={colors.accent}/></View><View style={{flex:1}}><Text style={styles.title}>{data?.digilocker.configured?'DigiLocker authorization available':'Demo DigiLocker Flow'}</Text><Text style={styles.copy}>{data?.digilocker.configured?'Connect only after reviewing the requested documents and consent.':'Prototype Integration · no live DigiLocker credentials are configured.'}</Text></View></View><ActionButton title={data?.digilocker.connected?'Review connection status':'Review document consent'} onPress={()=>router.push('/connect')}/></Card>
  {data?.profile.stVerified===true?<Card><View style={styles.row}><Icon name="badge-check" color={colors.verified}/><View style={{flex:1}}><Text style={styles.title}>ST certificate verification result</Text><Text style={styles.copy}>{data.profile.stVerificationMessage||'Result returned by the configured verification flow.'}</Text></View><StatusPill label="Verified" tone="verified"/></View></Card>:data?.profile.stVerified===false?<Card><View style={styles.row}><Icon name="circle-alert" color={colors.error}/><View style={{flex:1}}><Text style={styles.title}>Verification needs attention</Text><Text style={styles.copy}>{data.profile.stVerificationMessage||'Review the mismatch or request a manual official check.'}</Text></View></View><Text style={styles.manual}>A mismatch is not a finding that the document is fake. Use the authorized issuer process or manual review.</Text></Card>:null}
  {documents.map(document=>{const verified=document.verificationState==='verified'||document.status==='Verified'||document.status==='Verified ST Certificate';const source=document.sourceType==='user-upload'?'User-uploaded':document.sourceType==='issuer'?'Issuer-issued':document.sourceType==='digilocker'||document.issuer==='DigiLocker'?'DigiLocker document':document.issuer==='Prototype sample'?'Prototype sample':'Source not specified';return <Card key={document.id}><View style={styles.row}><View style={styles.tile}><Icon name="document-text-outline" color={colors.accent}/></View><View style={{flex:1}}><Text style={styles.title}>{document.name}</Text><Text style={styles.copy}>Source: {source} · {document.issuer}</Text><View style={{marginTop:7}}><StatusPill label={document.status} tone={verified?'verified':document.verificationState==='mismatch'?'error':'pending'}/></View></View></View>{document.updated?<Text style={styles.updated}>Document date: {document.updated}</Text>:null}{document.lastRetrievedAt?<Text style={styles.updated}>Last retrieved: {document.lastRetrievedAt}</Text>:null}{!verified?<><Text style={styles.manual}>Manual verification may be required. OCR or field matching cannot establish document authenticity.</Text><Pressable accessibilityRole="button" accessibilityState={{disabled:checking===document.id}} onPress={()=>void checkSource(document)} disabled={checking===document.id} style={styles.verifyButton}><Text style={styles.link}>{checking===document.id?'Checking source…':'Check authorized source'}</Text></Pressable>{results[document.id]?<Text accessibilityLiveRegion="polite" style={styles.manual}>{results[document.id]}</Text>:null}</>:null}</Card>})}
  {!documents.length?<Card><View style={styles.center}><Icon name="document-text-outline" size={28} color={colors.accent}/><Text style={styles.title}>No documents in your wallet</Text><Text style={styles.copy}>Select documents through the consent flow or add them through a supported authorized source. This prototype does not treat DigiLocker login as ST verification.</Text><ActionButton title="Choose documents and review consent" onPress={()=>router.push('/connect')}/></View></Card>:null}
  <Card><View style={styles.row}><Icon name="information-circle-outline" color={colors.accent}/><Text style={styles.copy}>Scheme-specific required documents are not configured. Confirm the current list with the relevant official scheme source.</Text></View></Card>
  <Pressable accessibilityRole="button" onPress={()=>router.push('/integrations')} style={styles.integrations}><Text style={styles.link}>View verification & integration status</Text><Icon name="chevron-forward" size={17}/></Pressable>
</Page>}
const styles=createThemedStyles((theme) => ({row:{flexDirection:'row',alignItems:'center',gap:11},tile:{width:42,height:42,borderRadius:13,backgroundColor:theme.surfaceStrong,alignItems:'center',justifyContent:'center'},title:{fontSize:13,fontWeight:'800',color:theme.textPrimary},copy:{fontSize:10,color:theme.textMuted,lineHeight:16,marginTop:4,flex:1},updated:{marginLeft:53,color:theme.textMuted,fontSize:10,marginTop:9},manual:{fontSize:10,lineHeight:15,color:theme.warning,marginTop:10},verifyButton:{alignSelf:'flex-start',paddingVertical:7,paddingHorizontal:3},center:{alignItems:'center',paddingVertical:8},integrations:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,paddingVertical:12},link:{fontSize:12,color:theme.accent,fontWeight:'700'}}));
