import { useRouter } from 'expo-router';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Card } from '../../src/components/Card';
import { Page } from '../../src/components/Page';
import { StatusPill } from '../../src/components/StatusPill';
import { Icon } from '../../src/components/Icon';
import { useApp } from '../../src/context/AppContext';
import { useNotifications } from '../../src/context/NotificationContext';
import { useProfilePhoto } from '../../src/context/ProfilePhotoContext';
import { colors, createThemedStyles } from '../../src/theme';
import { t } from '../../src/i18n';

export default function HomeScreen(){
  const {data}=useApp();const router=useRouter();const {unreadCount}=useNotifications();const {uri:profilePhotoUri}=useProfilePhoto();if(!data)return null;
  const profile=data.profile;
  const latestApplication=data.applications[0];
  const savedDraftId=Object.keys(data.drafts||{})[0];
  const savedDraftScheme=data.scholarships.find(scheme=>scheme.id===savedDraftId);
  const actions=data.applications.flatMap(application=>(application.pendingActions||[]).map(action=>({...action,applicationName:application.name})));
  const needsReview=data.documents.filter(document=>document.manualReviewRequired||document.verificationState==='manual-review'||document.verificationState==='mismatch').length;
  const paymentRecords=data.applications.filter(application=>application.paymentStatus);
  return <Page>
    <View style={styles.greet}><View><Text style={styles.namaste}>{t(data.settings.language,'Welcome')}</Text><Text style={styles.welcome}>{profile.name||'Student'}</Text></View><View style={styles.headerActions}><Pressable style={styles.headerButton} accessibilityRole="button" accessibilityLabel={unreadCount?`Notifications, ${unreadCount} unread`:'Notifications'} onPress={()=>router.push('/notifications' as never)}><Icon name="notifications-outline" size={24} color={colors.textSecondary}/>{unreadCount>0?<View style={styles.badge}/>:null}</Pressable><Pressable style={styles.headerButton} accessibilityRole="button" accessibilityLabel="Choose profile picture" onPress={()=>router.push('/profile-photo')}>{profilePhotoUri?<Image source={{uri:profilePhotoUri}} style={styles.profilePhotoThumb}/>:<Icon name="person-outline" size={24} color={colors.primary}/>}</Pressable></View></View>
    <Text style={styles.sectionHeading}>Scholarship Passport</Text>
    <Pressable onPress={()=>router.push('/passport')}><Card><View style={styles.row}><View style={styles.tile}><Icon name="shield-checkmark-outline" size={22}/></View><View style={{flex:1}}><Text style={styles.cardTitle}>{profile.connected?'Prototype profile':'Set up your reusable profile'}</Text><Text style={styles.muted}>{profile.connected?'Review details before reusing them':'Review or edit the sample profile details.'}</Text></View><Icon name="chevron-forward"/></View><View style={styles.stats}><View><Text style={styles.statNum}>{data.documents.length}</Text><Text style={styles.muted}>Documents</Text></View><View><Text style={styles.statNum}>{data.applications.length}</Text><Text style={styles.muted}>Applications</Text></View><View><Text style={styles.statNum}>{needsReview}</Text><Text style={styles.muted}>Manual review</Text></View></View></Card></Pressable>
    <View style={styles.section}><Text style={styles.sectionHeading}>My Applications</Text><Pressable onPress={()=>router.push('/applications')}><Text style={styles.link}>View all</Text></Pressable></View>
    {savedDraftScheme?<Pressable onPress={()=>router.push({pathname:'/apply/[id]',params:{id:savedDraftScheme.id}})}><Card><View style={styles.row}><View style={styles.tile}><Icon name="clipboard-pen"/></View><View style={{flex:1}}><Text style={styles.cardTitle}>Continue {savedDraftScheme.name}</Text><Text style={styles.muted}>Saved application draft · review before continuing</Text></View><Icon name="chevron-forward"/></View></Card></Pressable>:null}
    {latestApplication?<Pressable onPress={()=>router.push('/applications')}><Card><View style={styles.row}><View style={styles.tile}><Icon name="clipboard-check"/></View><View style={{flex:1}}><Text style={styles.cardTitle}>{latestApplication.name}</Text><Text style={styles.muted}>Current stage: {latestApplication.stage}</Text></View><StatusPill label={latestApplication.status} tone="info"/></View><Text style={styles.sampleLabel}>Prototype application data · not an official portal update</Text></Card></Pressable>:!savedDraftScheme?<Card><Text style={styles.muted}>No application has been recorded. Browse the five schemes to get started.</Text><Pressable onPress={()=>router.push('/(tabs)/scholarships')} style={styles.inlineAction}><Text style={styles.link}>Explore scholarships</Text><Icon name="chevron-forward" size={17}/></Pressable></Card>:null}
    <View style={styles.section}><Text style={styles.sectionHeading}>Pending actions</Text><Pressable onPress={()=>router.push('/applications')}><Text style={styles.link}>Review</Text></Pressable></View>
    <Pressable onPress={()=>router.push('/applications')}><Card><View style={styles.row}><View style={styles.tile}><Icon name={actions.length?'clock-3':'information-circle-outline'} color={actions.length?colors.warning:colors.accent}/></View><View style={{flex:1}}><Text style={styles.cardTitle}>{actions.length?`${actions.length} configured action${actions.length===1?'':'s'}`:'No pending action data'}</Text><Text style={styles.muted}>{actions.length?actions[0].title:'No action or deficiency has been received from an official source in this prototype.'}</Text></View><Icon name="chevron-forward"/></View></Card></Pressable>
    <View style={styles.section}><Text style={styles.sectionHeading}>Documents & Payment / DBT</Text></View>
    <View style={styles.twoCards}><Pressable style={styles.half} onPress={()=>router.push('/(tabs)/documents')}><Card><Icon name="document-text-outline" color={colors.accent}/><Text style={styles.cardTitle}>Document wallet</Text><Text style={styles.muted}>{data.documents.length} saved · {needsReview} require review</Text></Card></Pressable><Pressable style={styles.half} onPress={()=>router.push('/payments')}><Card><Icon name="landmark" color={colors.accent}/><Text style={styles.cardTitle}>Payment / DBT</Text><Text style={styles.muted}>{paymentRecords.length?`${paymentRecords.length} configured status`:'No payment status connected'}</Text></Card></Pressable></View>
    <Pressable onPress={()=>router.push('/(tabs)/assistant')}><Card style={styles.jagoCard}><View style={styles.row}><View style={styles.tile}><Icon name="bot-outline" color={colors.accent}/></View><View style={{flex:1}}><Text style={styles.cardTitle}>Ask JAGO</Text><Text style={styles.muted}>Scholarship, documents, application status and next steps</Text></View><Icon name="chevron-forward"/></View></Card></Pressable>
  </Page>
}
const styles=createThemedStyles((theme) => ({greet:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:15,backgroundColor:theme.primaryPressed,borderRadius:14,paddingHorizontal:14,paddingVertical:12},headerActions:{flexDirection:'row',alignItems:'center',gap:8},headerButton:{width:42,height:42,borderRadius:13,backgroundColor:theme.surface,alignItems:'center',justifyContent:'center',position:'relative',overflow:'hidden'},profilePhotoThumb:{width:42,height:42,borderRadius:13},badge:{position:'absolute',right:8,top:7,width:9,height:9,borderRadius:5,backgroundColor:theme.primary,borderWidth:1.5,borderColor:theme.surface},namaste:{fontSize:12,color:'#C7D7E8'},welcome:{fontSize:21,fontWeight:'800',color:'#FFFFFF',marginTop:3},sectionHeading:{fontSize:14,fontWeight:'800',color:theme.textPrimary},row:{flexDirection:'row',alignItems:'center',gap:11},tile:{width:42,height:42,borderRadius:13,backgroundColor:theme.surfaceStrong,alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:12,fontWeight:'800',color:theme.textPrimary,marginTop:5},muted:{fontSize:10,color:theme.textMuted,marginTop:4,lineHeight:15},stats:{flexDirection:'row',justifyContent:'space-around',marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:theme.border},statNum:{fontSize:15,fontWeight:'800',color:theme.accent,textAlign:'center'},section:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:5,marginBottom:5},link:{fontSize:11,fontWeight:'700',color:theme.accent},sampleLabel:{fontSize:9,color:theme.textMuted,marginTop:9},inlineAction:{flexDirection:'row',alignItems:'center',gap:5,marginTop:10},twoCards:{flexDirection:'row',gap:0},half:{flex:1,minWidth:0},jagoCard:{paddingVertical:12}}));
