import { useLocalSearchParams, useRouter } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import { ActionButton } from '../../src/components/ActionButton';
import { Card } from '../../src/components/Card';
import { Heading, Page } from '../../src/components/Page';
import { StatusPill } from '../../src/components/StatusPill';
import { Icon } from '../../src/components/Icon';
import { useApp } from '../../src/context/AppContext';
import { colors, createThemedStyles } from '../../src/theme';

export default function ScholarshipDetails(){const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const {data}=useApp();const scholarship=data?.scholarships.find(s=>s.id===id);const application=data?.applications.find(a=>a.scholarshipId===id);const draft=Boolean(data?.drafts?.[id]);if(!scholarship)return <Page><Heading title="Scholarship not found" subtitle="This scheme is not in the current catalogue."/></Page>;
return <Page><Heading eyebrow="SCHOLARSHIP MODULE" title={scholarship.name} subtitle={scholarship.level}/>
  <Card><View style={styles.top}><Text style={styles.section}>Eligibility guidance</Text><StatusPill label={application?.status||scholarship.status||'More Information Required'} tone="pending"/></View><Text style={styles.description}>No official eligibility rules are configured for this scheme in the current prototype. JAGO can collect and confirm your answers, but ADI SETU cannot make an official eligibility decision.</Text><View style={styles.divider}/><Text style={styles.section}>Required documents</Text>{scholarship.requiredDocuments?.length?scholarship.requiredDocuments.map(item=>{const saved=data?.documents.find(document=>document.name.toLowerCase()===item.toLowerCase());return <View style={styles.check} key={item}><Icon name={saved?'document-text-outline':'clock-3'} size={17} color={saved?colors.accent:colors.warning}/><View style={{flex:1}}><Text style={styles.description}>{item}</Text><Text style={saved?styles.available:styles.missing}>{saved?`In wallet · ${saved.status}`:'Missing from wallet'}</Text></View></View>}):<Text style={styles.description}>Scheme-specific document requirements are not configured here. Check the current official scheme information before applying.</Text>}</Card>
  {scholarship.range||scholarship.deadline?<Card><Text style={styles.section}>Configured scheme information</Text>{scholarship.range?<Text style={styles.description}>Award details: {scholarship.range}</Text>:null}{scholarship.deadline?<Text style={styles.description}>Deadline: {scholarship.deadline}</Text>:null}</Card>:null}
  {application?<Card><Text style={styles.section}>Your application</Text><Text style={styles.description}>Status shown: {application.status}</Text><Text style={styles.description}>Current stage: {application.stage}</Text><Text style={styles.disclaimer}>Application data in this prototype is not a government portal status.</Text><ActionButton title="Track application" onPress={()=>router.push('/applications')}/></Card>:null}
  {application||draft?<ActionButton title={draft?'Continue saved draft':application?'Continue application':'Start application'} onPress={()=>router.push({pathname:'/apply/[id]',params:{id:scholarship.id}})}/>:<><ActionButton title="Check with JAGO" onPress={()=>router.push('/(tabs)/assistant')}/><ActionButton title="Start application" secondary onPress={()=>router.push({pathname:'/apply/[id]',params:{id:scholarship.id}})}/></>}
</Page>}
const styles=createThemedStyles((theme) => ({top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},section:{fontSize:13,fontWeight:'800',color:theme.textPrimary},description:{fontSize:11,color:theme.textMuted,lineHeight:17,marginTop:9},available:{fontSize:10,color:theme.accent,marginTop:4},missing:{fontSize:10,color:theme.warning,marginTop:4},disclaimer:{fontSize:10,color:theme.warning,lineHeight:15,marginTop:8},divider:{height:1,backgroundColor:theme.border,marginVertical:13},check:{flexDirection:'row',gap:9,alignItems:'center'}}));
